name: Sync-ArticlesMap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: Create ArticlesMaps
        run: |
          cd content
          node ../articlesMaps.js
          echo "Running"
      - name: Push
        run: |
          git config user.name ArticleManager
          git config user.email developers@group.blogbooks.net
          git add .
          git commit -m "generated"
          git push
      - name: Task Ended
        run: echo "Task Ended"
